### PR TITLE
Emulator modification

### LINKED ISSUE #29: Modify the emulator
**User Stories** 

As a developer of the project, I want an emulated  environment to test the features of my car.

**Acceptance Criteria**

- There is an emulated environment with roads and obstacles to drive the car on.
- There is collision where appropriate.

### PR DESCRIPTION
**Pull request by Aditya-Nair-gu**
Closes #29

Implemented mods for the emulator by adding objects, roads and trees to imitate a city environment.

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by ErgiGU** [comment]
Needs more roads and obstacles

**Comment by RuthgerD** [comment]
Dont add the .import folder to github please

**Comment by ErgimanGU** [comment]
This is tied to the obstacle avoidance milestone because the emulator mod is created for that exact purpose

**Review by ErgiGU — APPROVED** [review]
Tested it and everything is displayed correctly, good job!

**Pull request merged**
